apiVersion: apps/v1
kind: Deployment
metadata:
  name: mamamech-rocks
  namespace: mamamech
  labels:
    app: mamamech-rocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mamamech-rocks
  template:
    metadata:
      labels:
        app: mamamech-rocks
    spec:
      containers:
        - name: mamamech-rocks
          image: ghcr.io/gorlah/mamamech.rocks:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mamamech-rocks
  namespace: mamamech
spec:
  selector:
    app: mamamech-rocks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mamamech-rocks
  namespace: mamamech
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mamamech.rocks
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: mamamech-rocks
                port:
                  number: 80
            path: /
  tls:
    - hosts:
        - mamamech.rocks
      secretName: mamamech-rocks-tls-secret
